#!/bin/sh
# Mock educativo de lsblk - Lista dispositivos de bloque
# Simula la salida de lsblk con datos de ejemplo

cat << 'EOF'
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda      8:0    0   100G  0 disk
├─sda1   8:1    0     1G  0 part /boot
├─sda2   8:2    0    50G  0 part /
└─sda3   8:3    0    49G  0 part /home
sr0     11:0    1  1024M  0 rom
EOF

exit 0
